### ISSUE TITLE
Can't report steps as logs

### ISSUE THREAD

**Issue by kycyyy** [reportportal/agent-js-webdriverio#32]
I have tried to set cucumberNestedSteps to true. And I got the following errors

`[0-0] Error: Request failed with status code 400: {"errorCode":40019,"message":"Test item status is ambiguous. There is no status provided from request and there are no descendants to check statistics for test item id '1140'"}

[0-0]     at /node_modules/@reportportal/client-javascript/lib/rest.js:37:15

[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)

[0-0] Error: Request failed with status code 400: {"errorCode":40019,"message":"Test item status is ambiguous. There is no status provided from request and there are no descendants to check statistics for test item id '1140'"}

[0-0]     at /node_modules/@reportportal/client-javascript/lib/rest.js:37:15

[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)

[0-0] Error: Request failed with status code 400: {"errorCode":40019,"message":"Test item status is ambiguous. There is no status provided from request and there are no descendants to check statistics for test item id '1140'"}

[0-0]     at /node_modules/@reportportal/client-javascript/lib/rest.js:37:15

[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)`

Any ideas? I want to aggregate test results per run instead of per spec. Right now, the report portal can only collect results per spec.

**Comment by AmsterGet** [comment]
Hello @kycyyy!
Could you provide the additional information that @tr1ble requested? It would also be very helpful if you could share a reproducible sample of this issue.
Thank you!

**Comment by AmsterGet** [comment]
Hello @kycyyy !
Is that issue still relevant to you?

**Comment by umarkhanTR** [comment]
I am using this statement from github and i can't see it on report portal
const { ReportingApi } = require('@reportportal/agent-js-webdriverio');
ReportingApi.info('suite INFO message log', null, 'Logs attaching. Launch, suite and tests with different logs');

i put this logging statement inside before and inside tests. none of them being seen on report portal

**Comment by AmsterGet** [comment]
Hi @umarkhanTR !
Did you face any errors?
You can check our [examples repo](https://github.com/reportportal/examples-js/tree/main/example-webdriverio) to see it in action.

**Comment by AmsterGet** [comment]
Hello there.
As we have been unable to reproduce the issue without extra information, I am closing this ticket.
Please feel free to reopen it if any new information comes to light.
