### ISSUE TITLE
Launches left IN_PROGRESS for failed Test only

### ISSUE THREAD

**Issue by vishal14121996** [reportportal/agent-js-webdriverio#64]
Hi @AmsterGet,

I'm facing the same issue, when i'm executing the test, if the test getting failed, so for that test -launch will continuosly shows as in-progress..

Adding the debug logs & Screenshots for the same..

[0-0] Start launch with tempId sktwi10i7lzctpv6r {
[0-0] description: 'This is execution of CG Wdio Automation Test',
[0-0] attributes: [
[0-0] {
[0-0] key: 'agent',
[0-0] value: '@reportportal/agent-js-webdriverio|5.1.1',
[0-0] system: true
[0-0] }
[0-0] ],
[0-0] rerun: undefined,
[0-0] rerunOf: undefined,
[0-0] mode: 'DEFAULT',
[0-0] id: undefined
[0-0] }
[0-0] Success start launch with tempId sktwi10i7lzctpv6r { id: '48c13089-cfce-488a-99f2-629d453128b9', number: 51 }
[0-0] Start test item with tempId sktwi10i7lzctpv79 {
[0-0] startTime: 1722610337589,
[0-0] name: 'Suite to validate the login Page on qa',
[0-0] type: 'SUITE',
[0-0] codeRef: 'specs/customerSite/login_test.js/Suite to validate the login Page on qa',
[0-0] testCaseId: 'specs/customerSite/login_test.js/Suite to validate the login Page on qa',
[0-0] launchUuid: '48c13089-cfce-488a-99f2-629d453128b9'
[0-0] }
[0-0] Success start item with tempId sktwi10i7lzctpv79 {
[0-0] id: '459f2c21-7d62-4bb5-9f31-f905f0945a1d',
[0-0] uniqueId: 'auto:792742fe20bb9b9cc012693fbcfe3ce6'
[0-0] }
[0-0] Start test item with tempId sktwi10i7lzctpv7c {
[0-0] startTime: 1722610337591,
[0-0] name: 'Test Case to validate login screen when no credentials are entered',
[0-0] type: 'STEP',
[0-0] codeRef: 'specs/customerSite/login_test.js/Suite to validate the login Page on qa/Test Case to validate login screen when no credentials are entered',
[0-0] parameters: [ { key: 'browser', value: 'chrome.127_0_6533_89.mac' } ],
[0-0] testCaseId: 'specs/customerSite/login_test.js/Suite to validate the login Page on qa/Test Case to validate login screen when no credentials are entered[chrome.127_0_6533_89.mac]',
[0-0] launchUuid: '48c13089-cfce-488a-99f2-629d453128b9'
[0-0] }
[0-0] Success start item with tempId sktwi10i7lzctpv7c {
[0-0] id: 'd5f275c7-7c9d-462f-92a5-eb1dbd5e2be1',
[0-0] uniqueId: 'auto:419da67ec3279d23c195246fd40330de'
[0-0] }
[0-0] Finish all children for test item with tempId sktwi10i7lzctpv79
[0-0] 2024-08-02T14:54:35.157Z ERROR @wdio/runner: Error: Some reporters are still unsynced: Reporter
[0-0] at Timeout. (file:///Users/vishaltyagi/Documents/Project/automation-cg/wdio_e2e/node_modules/@wdio/runner/build/reporter.js:111:35)
[0-0] at listOnTimeout (node:internal/timers:573:17)
[0-0] at process.processTimers (node:internal/timers:514:7)
[0-0] FAILED in chrome - file:///specs/customerSite/login_test.js
Total Passed TCs --> 0
Test run complete. Attempting to merge launches.
Find launches with UUIDs to merge: 48c13089-cfce-488a-99f2-629d453128b9
Found launches: 182 [
{
owner: 'superadmin',
description: 'This is execution of CG Wdio Automation Test',
id: 182,
uuid: '48c13089-cfce-488a-99f2-629d453128b9',
name: 'cg_wdio_launch',
number: 51,
startTime: 1722610337570,
lastModified: 1722610338288,
status: 'IN_PROGRESS',
statistics: { executions: {}, defects: {} },
attributes: [],
mode: 'DEFAULT',
analysing: [],
approximateDuration: 105.6416,
hasRetries: false,
rerun: false
}
]
Merge launches with ids: 182 {
launches: [ 182 ],
mergeType: 'BASIC',
description: 'This is execution of CG Wdio Automation Test',
mode: 'DEFAULT',
name: 'cg_wdio_launch',
attributes: undefined,
endTime: 1722610475839,
extendSuitesDescription: true
}
Error merging launches with UUIDs: 48c13089-cfce-488a-99f2-629d453128b9 Error: Request failed with status code 406: {"errorCode":4063,"message":"Unable to perform operation for non-finished launch. Cannot merge launch '182' with status 'IN_PROGRESS'"}
URL: http://10.1.1.232:8080/api/v1/cg_wdio/launch/merge
method: POST
at /Users/vishaltyagi/Documents/Project/automation-cg/wdio_e2e/node_modules/@reportportal/client-javascript/lib/rest.js:43:15
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Object.onComplete (file:///Users/vishaltyagi/Documents/Project/automation-cg/wdio_e2e/wdio.conf.js:531:17)
at async file:///Users/vishaltyagi/Documents/Project/automation-cg/wdio_e2e/node_modules/@wdio/cli/build/utils.js:101:13
at async Promise.all (index 0)
at async Launcher.run (file:///Users/vishaltyagi/Documents/Project/automation-cg/wdio_e2e/node_modules/@wdio/cli/build/launcher.js:110:39)
Error: Request failed with status code 406: {"errorCode":4063,"message":"Unable to perform operation for non-finished launch. Cannot merge launch '182' with status 'IN_PROGRESS'"}
URL: http://10.1.1.232:8080/api/v1/cg_wdio/launch/merge
method: POST
at /Users/vishaltyagi/Documents/Project/automation-cg/wdio_e2e/node_modules/@reportportal/client-javascript/lib/rest.js:43:15
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Object.onComplete (file:///Users/vishaltyagi/Documents/Project/automation-cg/wdio_e2e/wdio.conf.js:531:17)
at async file:///Users/vishaltyagi/Documents/Project/automation-cg/wdio_e2e/node_modules/@wdio/cli/build/utils.js:101:13
at async Promise.all (index 0)
at async Launcher.run (file:///Users/vishaltyagi/Documents/Project/automation-cg/wdio_e2e/node_modules/@wdio/cli/build/launcher.js:110:39)
Screenshot 2024-08-02 at 11 01 55 AM

**Comment by AmsterGet** [comment]
Hello @vishal14121996 !
It looks like wdio finished the reporter's process before it uploaded all the results to ReportPortal.
Try to increase the [`reporterSyncTimeout`](https://webdriver.io/docs/configuration/#reportersynctimeout) in your wdio configuration.

**Comment by vishal14121996** [comment]
> Hello @vishal14121996 ! It looks like wdio finished the reporter's process before it uploaded all the results to ReportPortal. Try to increase the [`reporterSyncTimeout`](https://webdriver.io/docs/configuration/#reportersynctimeout) in your wdio configuration.

Hi @AmsterGet 
i set the reportersynctimeout: 100000, still gives the same problem.
